apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: patient-service-v1
  labels:
    app: patient-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
      - name: patient-service
        image: patient-service:latest # Replace with your container registry path
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: patient-service-v1
spec:
  selector:
    app: patient-service
  ports:
  - port: 8080
    targetPort: 8084

